services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-site
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    external: true
